const cartItems = [
    {
        "id": 1,
        "name": "Clásica",
        "base": "Mix de verdes",
        "dressing": "Ranch",
        "description": "Mix de verdes, pollo, huevo, zanahoria, queso sardo rayado, tomates cherrys y aderezo ranch.",
        "image": "/img/Clásica.jpg",
        "price": 850,
        "status": "Mas Vendido",
        "amount": 10,
    },
    {
        "id": 2,
        "name": "Cala",
        "base": "Rúcula y fideos(penne rigatti)",
        "dressing": "Mostaza y miel",
        "description": "Rúcula, penne rigatti, pollo, tomates secos, nueces, queso azul y aderezo de mostaza y miel.",
        "image": "/img/Cala.jpg",
        "price": 850,
        "status": "Mas Vendido",
        "amount": 9,
    },
    {
        "id": 3,
        "name": "Caesar",
        "base": "Mix de verdes",
        "dressing": "Caesar",
        "description": "Mix de verdes, pollo, croûtons, queso sardo rayado, tomates cherrys y aderezo caesar.",
        "image": "/img/Caesar.jpg",
        "price": 850,
        "status": "Mas Vendido",
        "amount": 6,
    },
    {
        "id": 4,
        "name": "Crispy",
        "base": "Mix de verdes",
        "dressing": "Caesar",
        "description": "Mix de verdes, pollo rebozado con pan rallado y copos de maiz, croûtons, queso sardo rayado, tomates cherrys y aderezo caesar.",
        "image": "/img/Crispy.jpg",
        "price": 950,
        "status": "Mas Vendido",
        "amount": 10,
    },
    {
        "id": 5,
        "name": "Pastrón",
        "base": "Rúcula y fideos(penne rigatti)",
        "dressing": "Reducción de aceto balsámico",
        "description": "Rúcula, penne rigatti, pastrón feteado, queso tybo en cubos, morron rojo de conserva, nueces y reducción dulce de aceto balsámico.",
        "image":  "/img/Salami.jpg",
        "price": 970,
        "status": " ",
        "amount": 7,
    },
    {
        "id": 6,
        "name": "Peras",
        "base": "Peras",
        "dressing": "Vinagreta (Oliva, Aceto, Vinagre y Pimienta)",
        "description": "Rúcula, pollo, queso azul, nueces, peras en almíbar y vinagreta.",
        "image":  "/img/Peras.jpg",
        "price": 850,
        "status": " ",
        "amount": 8,
    },
    {
        "id": 8,
        "name": "Crudo",
        "base": "Rúcula y fideos(penne rigatti)",
        "dressing": "Reducción dulce de aceto balsámico y pesto genovés",
        "description": "Rúcula, penne rigatti, jamón crudo feteado, queso mozzarela en trozos, tomates secos, reducción dulce de aceto balsámico y pesto genovés.",
        "image": "/img/Crudo.jpg",
        "price": 1000,
        "status": " ",
        "amount": 11,
    },
    {
        "id": 9,
        "name": "Brie",
        "base": "Mix de verdes",
        "dressing": "Mostaza y miel",
        "description": "Mix de verdes, pollo, queso brie, tomates cherrys, croûtons, nueces, y aderezo de mostaza y miel.",
        "image": "/img/Brie.jpg",
        "price": 870,
        "status": "Mas Vendido",
        "amount": 0,
    },
    {
        "id": 10,
        "name": "Atún",
        "base": "Atún",
        "dressing": "Vinagreta",
        "description": "Mix de verdes, atún de lata (en lomitos), brócoli, arroz yamani, tomates cherrys, cebolla morada y vinagreta.",
        "image": "/img/Atun.JPG",
        "price": 850,
        "status": " ",
        "amount": 3,
    },
    {
        "id": 11,
        "name": "Frutilla",
        "base": "Rúcula",
        "dressing": "Reducción de Aceto Balsámico",
        "description": "Rúcula, frutilla, panceta, queso brie, nueces y reducción dulce de aceto balsámico.",
        "image": "/img/Frutillas.png",
        "price": 870,
        "status": " ",
        "amount": 2,
        
    }
]
 export default cartItems